<<<<<<< HEAD
# Generated by Django 2.2.7 on 2019-12-02 10:20
=======
# Generated by Django 2.2.7 on 2019-12-02 11:22
>>>>>>> ec526d6fa3b2119d5451389f0654577e7a6ead34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
<<<<<<< HEAD
                ('date', models.DateTimeField(verbose_name='date published')),
=======
                ('date', models.DateTimeField(verbose_name='data published')),
>>>>>>> ec526d6fa3b2119d5451389f0654577e7a6ead34
            ],
        ),
    ]
