# Generated by Django 2.2.7 on 2019-12-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phish',
        ),
    ]
