# Generated by Django 2.2.7 on 2019-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detector', '0002_delete_phish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Black',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_id', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
